
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 09 23:13:29 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 41;
  public static final int LBRACKET = 38;
  public static final int GREATER_OR_EQUAL = 18;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 16;
  public static final int LPAREN = 34;
  public static final int GREATER = 20;
  public static final int SEMI = 32;
  public static final int CONTINUE = 11;
  public static final int NUM_CONST = 42;
  public static final int LESS = 19;
  public static final int MINUS = 27;
  public static final int RPAREN = 35;
  public static final int AND = 21;
  public static final int LESS_OR_EQUAL = 17;
  public static final int OR = 22;
  public static final int COMMA = 33;
  public static final int INC = 24;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int ASSIGN = 23;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 15;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 28;
  public static final int MOD = 30;
  public static final int IDENT = 43;
  public static final int BREAK = 10;
  public static final int VOID = 14;
  public static final int COLON = 31;
  public static final int LBRACE = 36;
  public static final int ELSE = 7;
  public static final int READ = 3;
  public static final int WHILE = 9;
  public static final int RBRACE = 37;
  public static final int BOOL_CONST = 40;
  public static final int DEC = 25;
  public static final int PRINT = 4;
  public static final int DO = 8;
}

