
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Aug 28 17:22:50 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 44;
  public static final int LBRACKET = 38;
  public static final int GREATER_OR_EQUAL = 19;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 17;
  public static final int LPAREN = 34;
  public static final int GREATER = 21;
  public static final int SEMI = 32;
  public static final int CONTINUE = 12;
  public static final int NUM_CONST = 43;
  public static final int LESS = 20;
  public static final int FOR = 8;
  public static final int MINUS = 28;
  public static final int RPAREN = 35;
  public static final int COALESCE = 40;
  public static final int AND = 22;
  public static final int LESS_OR_EQUAL = 18;
  public static final int OR = 23;
  public static final int COMMA = 33;
  public static final int INC = 25;
  public static final int DIV = 30;
  public static final int QUESTION_MARK = 41;
  public static final int PLUS = 27;
  public static final int ASSIGN = 24;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 16;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 29;
  public static final int MOD = 31;
  public static final int IDENT = 46;
  public static final int BREAK = 11;
  public static final int VOID = 15;
  public static final int COLON = 42;
  public static final int LBRACE = 36;
  public static final int ELSE = 7;
  public static final int READ = 3;
  public static final int WHILE = 10;
  public static final int RBRACE = 37;
  public static final int BOOL_CONST = 45;
  public static final int DEC = 26;
  public static final int PRINT = 4;
  public static final int DO = 9;
}

